2017-11-03 18:12:54,773 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-03 18:12:54,774 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-11-03 18:12:54,804 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.7.0-x86_64-i386-64bit
2017-11-03 18:12:54,804 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-03 18:12:54,816 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.10
2017-11-03 18:12:54,817 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-03 18:12:54,817 [ERROR] mongo_connector.connector:373 - No replica set at "localhost:27017"! A replica set is required to run mongo-connector. Shutting down...
2017-11-03 18:15:29,315 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-03 18:15:29,315 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-11-03 18:15:29,339 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.7.0-x86_64-i386-64bit
2017-11-03 18:15:29,339 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-03 18:15:29,361 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.10
2017-11-03 18:15:29,361 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-03 18:15:29,362 [ERROR] mongo_connector.connector:373 - No replica set at "localhost:27017"! A replica set is required to run mongo-connector. Shutting down...
2017-11-03 18:17:43,332 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-03 18:17:43,332 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-11-03 18:17:43,357 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.7.0-x86_64-i386-64bit
2017-11-03 18:17:43,358 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-03 18:17:43,383 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.10
2017-11-03 18:17:43,383 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-03 18:17:43,384 [ERROR] mongo_connector.connector:373 - No replica set at "localhost:27017"! A replica set is required to run mongo-connector. Shutting down...
2017-11-03 18:21:14,103 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-03 18:21:14,103 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-11-03 18:21:14,124 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.7.0-x86_64-i386-64bit
2017-11-03 18:21:14,124 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-03 18:21:14,130 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.10
2017-11-03 18:21:14,130 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-03 18:21:14,131 [ERROR] mongo_connector.connector:373 - No replica set at "localhost:27017"! A replica set is required to run mongo-connector. Shutting down...
2017-11-03 18:23:47,593 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-03 18:23:47,593 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-11-03 18:23:47,618 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.7.0-x86_64-i386-64bit
2017-11-03 18:23:47,619 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-03 18:23:47,624 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.10
2017-11-03 18:23:47,624 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-03 18:23:47,625 [ERROR] mongo_connector.connector:373 - No replica set at "localhost:27017"! A replica set is required to run mongo-connector. Shutting down...
2017-11-03 18:24:57,615 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-03 18:24:57,615 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-11-03 18:24:57,638 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.7.0-x86_64-i386-64bit
2017-11-03 18:24:57,638 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-03 18:24:57,643 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.10
2017-11-03 18:24:57,643 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-03 18:24:57,644 [ERROR] mongo_connector.connector:373 - No replica set at "localhost:27017"! A replica set is required to run mongo-connector. Shutting down...
2017-11-03 18:28:09,361 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-03 18:28:09,361 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-11-03 18:28:09,385 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.7.0-x86_64-i386-64bit
2017-11-03 18:28:09,385 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-03 18:28:39,633 [ERROR] mongo_connector.util:106 - Fatal Exception
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector/connector.py", line 347, in run
    self.main_conn.admin.command('buildInfo')['version'])
  File "/Library/Python/2.7/site-packages/pymongo/database.py", line 513, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/Library/Python/2.7/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/Library/Python/2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
2017-11-03 18:30:27,825 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-03 18:30:27,825 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-11-03 18:30:27,840 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.7.0-x86_64-i386-64bit
2017-11-03 18:30:27,840 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-03 18:30:27,849 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.10
2017-11-03 18:30:27,849 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-03 18:30:58,064 [ERROR] mongo_connector.util:106 - Fatal Exception
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector/connector.py", line 382, in run
    self.update_version_from_client(self.main_conn)
  File "/Library/Python/2.7/site-packages/mongo_connector/connector.py", line 334, in update_version_from_client
    is_master = client.admin.command("isMaster")
  File "/Library/Python/2.7/site-packages/pymongo/database.py", line 513, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/Library/Python/2.7/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/Library/Python/2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: No replica set members match selector "Primary()"
2017-11-03 18:31:10,244 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-03 18:31:10,244 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-11-03 18:31:10,264 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.7.0-x86_64-i386-64bit
2017-11-03 18:31:10,264 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-03 18:31:10,269 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.10
2017-11-03 18:31:10,269 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-03 18:31:40,495 [ERROR] mongo_connector.util:106 - Fatal Exception
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector/connector.py", line 382, in run
    self.update_version_from_client(self.main_conn)
  File "/Library/Python/2.7/site-packages/mongo_connector/connector.py", line 334, in update_version_from_client
    is_master = client.admin.command("isMaster")
  File "/Library/Python/2.7/site-packages/pymongo/database.py", line 513, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/Library/Python/2.7/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/Library/Python/2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: No replica set members match selector "Primary()"
2017-11-03 18:37:27,108 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-03 18:37:27,108 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-11-03 18:37:27,123 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.7.0-x86_64-i386-64bit
2017-11-03 18:37:27,123 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-03 18:37:27,128 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.10
2017-11-03 18:37:27,128 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-03 18:37:57,339 [ERROR] mongo_connector.util:106 - Fatal Exception
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector/connector.py", line 382, in run
    self.update_version_from_client(self.main_conn)
  File "/Library/Python/2.7/site-packages/mongo_connector/connector.py", line 334, in update_version_from_client
    is_master = client.admin.command("isMaster")
  File "/Library/Python/2.7/site-packages/pymongo/database.py", line 513, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/Library/Python/2.7/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/Library/Python/2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: No replica set members match selector "Primary()"
2017-11-03 18:37:58,611 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-03 18:37:58,611 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-11-03 18:37:58,637 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.7.0-x86_64-i386-64bit
2017-11-03 18:37:58,637 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-03 18:37:58,644 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.10
2017-11-03 18:37:58,644 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-03 18:38:28,864 [ERROR] mongo_connector.util:106 - Fatal Exception
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector/connector.py", line 382, in run
    self.update_version_from_client(self.main_conn)
  File "/Library/Python/2.7/site-packages/mongo_connector/connector.py", line 334, in update_version_from_client
    is_master = client.admin.command("isMaster")
  File "/Library/Python/2.7/site-packages/pymongo/database.py", line 513, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/Library/Python/2.7/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/Library/Python/2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: No replica set members match selector "Primary()"
