2017-11-22 14:57:54,498 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-22 14:57:54,512 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
2017-11-22 14:57:54,517 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.9.49-moby-x86_64-with-debian-8.7
2017-11-22 14:57:54,519 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-11-22 14:57:54,535 [WARNING] mongo_connector.connector:1260 - pymongo version 3.4.0 was installed without the C extensions. "InvalidBSON: Date value out of range" errors may occur if there are documents with BSON Datetimes that represent times outside of Python's datetime limit.
2017-11-22 14:57:55,091 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.4
2017-11-22 14:57:55,092 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-22 15:38:33,931 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-22 15:38:33,933 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
2017-11-22 15:38:33,937 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.9.49-moby-x86_64-with-debian-8.7
2017-11-22 15:38:33,938 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-11-22 15:38:33,951 [WARNING] mongo_connector.connector:1260 - pymongo version 3.4.0 was installed without the C extensions. "InvalidBSON: Date value out of range" errors may occur if there are documents with BSON Datetimes that represent times outside of Python's datetime limit.
2017-11-22 15:38:34,089 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.4
2017-11-22 15:38:34,090 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-22 15:49:40,358 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-22 15:49:40,360 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
2017-11-22 15:49:40,361 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.9.49-moby-x86_64-with-debian-8.7
2017-11-22 15:49:40,362 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-11-22 15:49:40,362 [WARNING] mongo_connector.connector:1260 - pymongo version 3.4.0 was installed without the C extensions. "InvalidBSON: Date value out of range" errors may occur if there are documents with BSON Datetimes that represent times outside of Python's datetime limit.
2017-11-22 15:49:40,440 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.4
2017-11-22 15:49:40,443 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-22 15:52:04,918 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-22 15:52:04,919 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
2017-11-22 15:52:04,924 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.9.49-moby-x86_64-with-debian-8.7
2017-11-22 15:52:04,925 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-11-22 15:52:04,926 [WARNING] mongo_connector.connector:1260 - pymongo version 3.4.0 was installed without the C extensions. "InvalidBSON: Date value out of range" errors may occur if there are documents with BSON Datetimes that represent times outside of Python's datetime limit.
2017-11-22 15:52:04,972 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.4
2017-11-22 15:52:04,973 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-22 15:53:57,333 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-22 15:53:57,334 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
2017-11-22 15:53:57,336 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.9.49-moby-x86_64-with-debian-8.7
2017-11-22 15:53:57,336 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-11-22 15:53:57,337 [WARNING] mongo_connector.connector:1260 - pymongo version 3.4.0 was installed without the C extensions. "InvalidBSON: Date value out of range" errors may occur if there are documents with BSON Datetimes that represent times outside of Python's datetime limit.
2017-11-22 15:53:57,384 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.4
2017-11-22 15:53:57,385 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-22 15:54:58,172 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-22 15:54:58,173 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
2017-11-22 15:54:58,174 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.9.49-moby-x86_64-with-debian-8.7
2017-11-22 15:54:58,175 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-11-22 15:54:58,175 [WARNING] mongo_connector.connector:1260 - pymongo version 3.4.0 was installed without the C extensions. "InvalidBSON: Date value out of range" errors may occur if there are documents with BSON Datetimes that represent times outside of Python's datetime limit.
2017-11-22 15:54:58,303 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.4
2017-11-22 15:54:58,303 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-22 16:30:05,491 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-22 16:30:05,492 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
2017-11-22 16:30:05,499 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.9.49-moby-x86_64-with-debian-8.7
2017-11-22 16:30:05,501 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-11-22 16:30:05,502 [WARNING] mongo_connector.connector:1260 - pymongo version 3.4.0 was installed without the C extensions. "InvalidBSON: Date value out of range" errors may occur if there are documents with BSON Datetimes that represent times outside of Python's datetime limit.
2017-11-22 16:30:06,414 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.4
2017-11-22 16:30:06,415 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-22 16:32:45,149 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-22 16:32:45,157 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
2017-11-22 16:32:45,161 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.9.49-moby-x86_64-with-debian-8.7
2017-11-22 16:32:45,162 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-11-22 16:32:45,162 [WARNING] mongo_connector.connector:1260 - pymongo version 3.4.0 was installed without the C extensions. "InvalidBSON: Date value out of range" errors may occur if there are documents with BSON Datetimes that represent times outside of Python's datetime limit.
2017-11-22 16:32:45,252 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.4
2017-11-22 16:32:45,253 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-22 16:37:04,126 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-22 16:37:04,131 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
2017-11-22 16:37:04,133 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.9.49-moby-x86_64-with-debian-8.7
2017-11-22 16:37:04,134 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-11-22 16:37:04,136 [WARNING] mongo_connector.connector:1260 - pymongo version 3.4.0 was installed without the C extensions. "InvalidBSON: Date value out of range" errors may occur if there are documents with BSON Datetimes that represent times outside of Python's datetime limit.
2017-11-22 16:37:04,368 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.4
2017-11-22 16:37:04,369 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-22 16:43:51,659 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-22 16:43:51,661 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
2017-11-22 16:43:51,665 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.9.49-moby-x86_64-with-debian-8.7
2017-11-22 16:43:51,666 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-11-22 16:43:51,666 [WARNING] mongo_connector.connector:1260 - pymongo version 3.4.0 was installed without the C extensions. "InvalidBSON: Date value out of range" errors may occur if there are documents with BSON Datetimes that represent times outside of Python's datetime limit.
2017-11-22 16:43:51,717 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.4
2017-11-22 16:43:51,718 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-22 16:55:26,337 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-22 16:55:26,338 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]
2017-11-22 16:55:26,339 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.9.49-moby-x86_64-with-debian-8.7
2017-11-22 16:55:26,342 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-11-22 16:55:26,343 [WARNING] mongo_connector.connector:1260 - pymongo version 3.4.0 was installed without the C extensions. "InvalidBSON: Date value out of range" errors may occur if there are documents with BSON Datetimes that represent times outside of Python's datetime limit.
2017-11-22 16:55:26,441 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.4
2017-11-22 16:55:26,441 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
